openapi: 3.0.3
info:
  title: KentKart API
  version: 1.0.11
servers:
  - url: https://service.kentkart.com/rl1/api/
tags:
  - name: info
paths:
  /info/announce:
    get:
      tags:
        - info
      parameters:
        - name: region
          in: query
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid ID supplied
        '404':
          description: Pet not found
        '405':
          description: Validation exception
          
  /v2.0/city:
    get:
      tags:
        - info
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid ID supplied
        '404':
          description: Pet not found
        '405':
          description: Validation exception